name: Code sink CI
on:
  push:
  pull_request:
jobs:
  check:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run format:check
      - name: Lint ng code
        run: npm run lint:ng:ci
      - name: Lint styles code
        run: npm run lint:styles
      - name: Test ng code
        run: npm run test:ci
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deploy_coverage
          path: coverage
  build:
    name: Build app
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Archive build
        if: success() && github.ref_name == 'main'
        uses: actions/upload-artifact@v3
        with:
          name: deploy_dist
          path: dist
  deploy:
    name: Deploy app
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: deploy_dist
          path: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy_dist/code-sink
  audit:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Audit
        run: npm run lh
